// <auto-generated />
using System;
using LY_WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LY_WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LY_WebApi.Models.Shirts", b =>
                {
                    b.Property<int>("ShirtsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShirtsId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtsId");

                    b.ToTable("shirt");

                    b.HasData(
                        new
                        {
                            ShirtsId = 1,
                            Brand = "品牌1",
                            Color = "黑",
                            Gender = "男",
                            GuidId = new Guid("00000000-0000-0000-0000-000000000001"),
                            MyProperty = 50,
                            Size = 5
                        },
                        new
                        {
                            ShirtsId = 2,
                            Brand = "品牌2",
                            Color = "黑",
                            Gender = "男",
                            GuidId = new Guid("00000000-0000-0000-0000-000000000002"),
                            MyProperty = 51,
                            Size = 5
                        },
                        new
                        {
                            ShirtsId = 3,
                            Brand = "品牌3",
                            Color = "黑",
                            Gender = "男",
                            GuidId = new Guid("00000000-0000-0000-0000-000000000003"),
                            MyProperty = 52,
                            Size = 5
                        },
                        new
                        {
                            ShirtsId = 4,
                            Brand = "品牌4",
                            Color = "黑",
                            Gender = "男",
                            GuidId = new Guid("00000000-0000-0000-0000-000000000004"),
                            MyProperty = 53,
                            Size = 5
                        },
                        new
                        {
                            ShirtsId = 5,
                            Brand = "品牌5",
                            Color = "黑",
                            Gender = "男",
                            GuidId = new Guid("00000000-0000-0000-0000-000000000005"),
                            MyProperty = 54,
                            Size = 5
                        },
                        new
                        {
                            ShirtsId = 6,
                            Brand = "品牌6",
                            Color = "黑",
                            Gender = "男",
                            GuidId = new Guid("00000000-0000-0000-0000-000000000006"),
                            MyProperty = 55,
                            Size = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
